# GENERATED by PathMap/tools/gen_spec_ops.jl from test/differential/spec/ops.toml (version 1).
# DO NOT EDIT. Change ops.toml and regenerate; the Lean side is generated from the same table.

const SPEC_VERSION = 1
const NOPS = 25
const OP_NAMES = ["descend_to", "descend_to_byte", "ascend", "ascend_byte", "reset", "descend_first_byte", "descend_last_byte", "descend_indexed_byte", "descend_until", "ascend_until", "ascend_until_branch", "to_next_sibling_byte", "to_prev_sibling_byte", "to_next_step", "to_next_val", "descend_first_k_path", "k_path_walk", "descend_last_path", "move_to_path", "descend_to_existing", "descend_to_val", "descend_to_existing_byte", "descend_until_max_bytes", "descend_to_check", "val_at"]

"""
    spec_step!(st, d) -> Bool

Decode and run one operation on `st.rz`, appending its trace line. `false` means the input ran out
mid-operation, which ends the program (same rule as the model).
"""
function spec_step!(st::SpecState, d::Dec)
    raw = dec_u8!(d)
    raw === nothing && return false
    op = Int(raw) % NOPS
    z = st.rz
    if op == 0   # descend_to
        a1 = dec_path!(d)
        a1 === nothing && return false
        sk = nothing
        emit!(st, "descend_to", sk === nothing ? ((zipper_descend_to!(z, a1); hex_path(a1))) : sk)
    elseif op == 1   # descend_to_byte
        a1 = dec_pathbyte!(d)
        a1 === nothing && return false
        sk = nothing
        emit!(st, "descend_to_byte", sk === nothing ? ((zipper_descend_to_byte!(z, a1); hex_byte(a1))) : sk)
    elseif op == 2   # ascend
        a1 = dec_mod!(d, 8)
        a1 === nothing && return false
        sk = nothing
        emit!(st, "ascend", sk === nothing ? (string(sp_ascend!(z, a1))) : sk)
    elseif op == 3   # ascend_byte
        sk = nothing
        emit!(st, "ascend_byte", sk === nothing ? (show_bool(zipper_ascend_byte!(z))) : sk)
    elseif op == 4   # reset
        sk = nothing
        emit!(st, "reset", sk === nothing ? ((zipper_reset!(z); "-")) : sk)
    elseif op == 5   # descend_first_byte
        sk = nothing
        emit!(st, "descend_first_byte", sk === nothing ? (show_byte_opt(sp_moved_byte(z, zipper_descend_first_byte!))) : sk)
    elseif op == 6   # descend_last_byte
        sk = nothing
        emit!(st, "descend_last_byte", sk === nothing ? (show_byte_opt(sp_moved_byte(z, zipper_descend_last_byte!))) : sk)
    elseif op == 7   # descend_indexed_byte
        a1 = dec_mod!(d, 6)
        a1 === nothing && return false
        sk = nothing
        emit!(st, "descend_indexed_byte", sk === nothing ? (show_byte_opt(sp_moved_byte(z, zz -> zipper_descend_indexed_byte!(zz, a1)))) : sk)
    elseif op == 8   # descend_until
        sk = nothing
        emit!(st, "descend_until", sk === nothing ? (show_bool(zipper_descend_until!(z))) : sk)
    elseif op == 9   # ascend_until
        sk = nothing
        emit!(st, "ascend_until", sk === nothing ? (string(sp_ascended(z, zipper_ascend_until!))) : sk)
    elseif op == 10   # ascend_until_branch
        sk = nothing
        emit!(st, "ascend_until_branch", sk === nothing ? (string(sp_ascended(z, zipper_ascend_until_branch!))) : sk)
    elseif op == 11   # to_next_sibling_byte
        sk = nothing
        emit!(st, "to_next_sibling_byte", sk === nothing ? (show_byte_opt(sp_moved_byte(z, zipper_to_next_sibling_byte!))) : sk)
    elseif op == 12   # to_prev_sibling_byte
        sk = nothing
        emit!(st, "to_prev_sibling_byte", sk === nothing ? (show_byte_opt(sp_moved_byte(z, zipper_to_prev_sibling_byte!))) : sk)
    elseif op == 13   # to_next_step
        sk = nothing
        emit!(st, "to_next_step", sk === nothing ? (show_bool(zipper_to_next_step!(z))) : sk)
    elseif op == 14   # to_next_val
        sk = nothing
        emit!(st, "to_next_val", sk === nothing ? (show_bool(zipper_to_next_val!(z))) : sk)
    elseif op == 15   # descend_first_k_path
        a1 = dec_mod!(d, 4)
        a1 === nothing && return false
        sk = (a1 == 0) ? "skip:k0" : (zipper_child_count(z) == 0) ? "skip:known-hang" : nothing
        emit!(st, "descend_first_k_path", sk === nothing ? (show_bool(zipper_descend_first_k_path!(z, a1))) : sk)
    elseif op == 16   # k_path_walk
        a1 = dec_mod!(d, 4)
        a1 === nothing && return false
        sk = (a1 == 0) ? "skip:k0" : (zipper_child_count(z) == 0) ? "skip:known-hang" : nothing
        emit!(st, "k_path_walk", sk === nothing ? (join(hex_path.(sp_k_walk!(z, a1)), ",")) : sk)
    elseif op == 17   # descend_last_path
        sk = nothing
        emit!(st, "descend_last_path", sk === nothing ? (show_bool(zipper_descend_last_path!(z))) : sk)
    elseif op == 18   # move_to_path
        a1 = dec_path!(d)
        a1 === nothing && return false
        sk = nothing
        emit!(st, "move_to_path", sk === nothing ? (string(zipper_move_to_path!(z, a1))) : sk)
    elseif op == 19   # descend_to_existing
        a1 = dec_path!(d)
        a1 === nothing && return false
        sk = nothing
        emit!(st, "descend_to_existing", sk === nothing ? (string(zipper_descend_to_existing!(z, a1))) : sk)
    elseif op == 20   # descend_to_val
        a1 = dec_path!(d)
        a1 === nothing && return false
        sk = nothing
        emit!(st, "descend_to_val", sk === nothing ? (string(zipper_descend_to_val!(z, a1))) : sk)
    elseif op == 21   # descend_to_existing_byte
        a1 = dec_pathbyte!(d)
        a1 === nothing && return false
        sk = nothing
        emit!(st, "descend_to_existing_byte", sk === nothing ? (show_bool(zipper_descend_to_existing_byte!(z, a1))) : sk)
    elseif op == 22   # descend_until_max_bytes
        a1 = dec_mod!(d, 8)
        a1 === nothing && return false
        sk = nothing
        emit!(st, "descend_until_max_bytes", sk === nothing ? (show_bool(zipper_descend_until_max_bytes!(z, a1))) : sk)
    elseif op == 23   # descend_to_check
        a1 = dec_path!(d)
        a1 === nothing && return false
        sk = nothing
        emit!(st, "descend_to_check", sk === nothing ? (show_bool(zipper_descend_to_check!(z, a1))) : sk)
    elseif op == 24   # val_at
        a1 = dec_path!(d)
        a1 === nothing && return false
        sk = nothing
        emit!(st, "val_at", sk === nothing ? (show_val(zipper_val_at(z, a1))) : sk)
    else
        emit!(st, "nop", "-")
    end
    true
end
