-- GENERATED by PathMap/tools/gen_spec_ops.jl from test/differential/spec/ops.toml (version 1).
-- DO NOT EDIT. Change ops.toml and regenerate; the Julia side is generated from the same table.
import PathMapsSpec.Fuzz

/-!
# Our op table (`pathmaps-oracle --spec`)

The model side of the PathMapsSpec harness: decodes the wire format described in `ops.toml`, runs each
operation on the model's read zipper, and prints one trace line per step plus the final maps.
-/

namespace PathMapsSpec
namespace SpecFuzz
open Fuzz

structure St where
  m0 : PathMap V
  rz : Zip V
  out : List String
  step : Nat

/-- Per-step fingerprint: relative path, origin, existence, value, child count, value count. -/
def fp (z : Zip V) : String :=
  hexPath z.path ++ " o" ++ hexPath z.focus ++ " e" ++ showBool z.pathExists ++
  " v" ++ showVal z.val ++ " c" ++ toString z.childCount ++ " n" ++ toString z.valCount

def emit (s : St) (z : Zip V) (name ret : String) : St :=
  { s with rz := z, step := s.step + 1,
           out := (toString s.step ++ " " ++ name ++ " ret=" ++ ret ++ " R=" ++ fp z) :: s.out }

def nops : Nat := 25

def step (s : St) (d : Dec) : Option (St × Dec) := do
  let (opRaw, d) ← d.u8
  let z := s.rz
  match opRaw.toNat % nops with
  | 0 => do
      let (a1, d) ← d.path
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_to" tok, d)
      | none =>
        let (ret, z) := ((hexPath a1, z.descendTo a1))
        some (emit s z "descend_to" ret, d)
  | 1 => do
      let (a1, d) ← d.pathByte
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_to_byte" tok, d)
      | none =>
        let (ret, z) := ((hexByte a1, z.descendToByte a1))
        some (emit s z "descend_to_byte" ret, d)
  | 2 => do
      let (a1, d) ← d.mod 8
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "ascend" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.ascend a1; (toString r, z))
        some (emit s z "ascend" ret, d)
  | 3 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "ascend_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.ascendByte; (showBool r, z))
        some (emit s z "ascend_byte" ret, d)
  | 4 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "reset" tok, d)
      | none =>
        let (ret, z) := (("-", z.reset))
        some (emit s z "reset" ret, d)
  | 5 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_first_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendFirstByte; (showByteOpt r, z))
        some (emit s z "descend_first_byte" ret, d)
  | 6 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_last_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendLastByte; (showByteOpt r, z))
        some (emit s z "descend_last_byte" ret, d)
  | 7 => do
      let (a1, d) ← d.mod 6
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_indexed_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendIndexedByte a1; (showByteOpt r, z))
        some (emit s z "descend_indexed_byte" ret, d)
  | 8 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_until" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendUntil; (showBool r, z))
        some (emit s z "descend_until" ret, d)
  | 9 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "ascend_until" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.ascendUntil; (toString r, z))
        some (emit s z "ascend_until" ret, d)
  | 10 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "ascend_until_branch" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.ascendUntilBranch; (toString r, z))
        some (emit s z "ascend_until_branch" ret, d)
  | 11 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "to_next_sibling_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.toNextSiblingByte; (showByteOpt r, z))
        some (emit s z "to_next_sibling_byte" ret, d)
  | 12 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "to_prev_sibling_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.toPrevSiblingByte; (showByteOpt r, z))
        some (emit s z "to_prev_sibling_byte" ret, d)
  | 13 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "to_next_step" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.toNextStep; (showBool r, z))
        some (emit s z "to_next_step" ret, d)
  | 14 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "to_next_val" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.toNextVal; (showBool r, z))
        some (emit s z "to_next_val" ret, d)
  | 15 => do
      let (a1, d) ← d.mod 4
      let sk : Option String := if (a1 == 0) then some "skip:k0" else if (z.childCount == 0) then some "skip:known-hang" else none
      match sk with
      | some tok => some (emit s z "descend_first_k_path" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendFirstKPath a1; (showBool r, z))
        some (emit s z "descend_first_k_path" ret, d)
  | 16 => do
      let (a1, d) ← d.mod 4
      let sk : Option String := if (a1 == 0) then some "skip:k0" else if (z.childCount == 0) then some "skip:known-hang" else none
      match sk with
      | some tok => some (emit s z "k_path_walk" tok, d)
      | none =>
        let (ret, z) := (let (ps, z) := kWalk z a1; (String.intercalate "," (ps.map hexPath), z))
        some (emit s z "k_path_walk" ret, d)
  | 17 => do
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_last_path" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendLastPath; (showBool r, z))
        some (emit s z "descend_last_path" ret, d)
  | 18 => do
      let (a1, d) ← d.path
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "move_to_path" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.moveToPath a1; (toString r, z))
        some (emit s z "move_to_path" ret, d)
  | 19 => do
      let (a1, d) ← d.path
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_to_existing" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendToExisting a1; (toString r, z))
        some (emit s z "descend_to_existing" ret, d)
  | 20 => do
      let (a1, d) ← d.path
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_to_val" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendToVal a1; (toString r, z))
        some (emit s z "descend_to_val" ret, d)
  | 21 => do
      let (a1, d) ← d.pathByte
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_to_existing_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendToExistingByte a1; (showBool r, z))
        some (emit s z "descend_to_existing_byte" ret, d)
  | 22 => do
      let (a1, d) ← d.mod 8
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_until_max_bytes" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendUntilMaxBytes a1; (showBool r, z))
        some (emit s z "descend_until_max_bytes" ret, d)
  | 23 => do
      let (a1, d) ← d.path
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "descend_to_check" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendToCheck a1; (showBool r, z))
        some (emit s z "descend_to_check" ret, d)
  | 24 => do
      let (a1, d) ← d.path
      let sk : Option String := none
      match sk with
      | some tok => some (emit s z "val_at" tok, d)
      | none =>
        let (ret, z) := ((showVal (z.valAt a1), z))
        some (emit s z "val_at" ret, d)
  | _ => some (emit s z "nop" "-", d)

def loop : Nat → St → Dec → St
  | 0, s, _ => s
  | n + 1, s, d =>
      match step s d with
      | some (s', d') => loop n s' d'
      | none => s

def header (d : Dec) : Option (St × Dec) := do
  let (n0, d) ← d.mod 8
  let (m0, d) ← seed PathMap.empty d n0
  let (n1, d) ← d.mod 8
  let (m1, d) ← seed PathMap.empty d n1
  let (r0, d) ← d.path 4
  let (r1, d) ← d.path 4
  let m0 := if r0.isEmpty then m0 else m0.addPath r0
  let m1 := if r1.isEmpty then m1 else m1.addPath r1
  some ({ m0 := m0, rz := { trie := m1, root := r1, path := [] }, out := [], step := 0 }, d)

/-- Decode and run an input; the trace lines, then the final maps. -/
def run (bytes : ByteArray) (maxSteps : Nat := 256) : List String :=
  match header { bytes, pos := 0 } with
  | none => ["EMPTY"]
  | some (s0, d) =>
      let s := loop maxSteps s0 d
      s.out.reverse ++
        [ "MAP0 " ++ dumpAt s.m0 [], "MAP1 " ++ dumpAt s.rz.trie [],
          "ROOT1 " ++ hexPath s.rz.root ]

end SpecFuzz
end PathMapsSpec
