-- GENERATED by PathMap/tools/gen_spec_ops.jl from test/differential/spec/ops.toml (version 4).
-- DO NOT EDIT. Change ops.toml and regenerate; the Julia side is generated from the same table.
import PathMapsSpec.Fuzz
import PathMapsSpec.Write

/-!
# Our op table (`pathmaps-oracle --spec`)

The model side of the PathMapsSpec harness: decodes the wire format described in `ops.toml`, runs each
operation on the model's write zipper (`wz`, over map0) or read zipper (`rz`, over map1), and prints one
trace line per step plus the final maps.
-/

set_option linter.unusedVariables false

namespace PathMapsSpec
namespace SpecFuzz
open Fuzz

/-- OUR `UInt64` lattice (`src/core/Ring.jl`): join = max, meet = min, subtract = saturating, with
the identity masks our implementation reports. Upstream's `u64Ops` is a placeholder we do not follow. -/
def ourOps : ValOps UInt64 where
  pjoin a b := if a == b then .identity true true else if a > b then .identity true false else .identity false true
  pmeet a b := if a == b then .identity true true else if a < b then .identity true false else .identity false true
  psub a b := if b >= a then .none else if b == 0 then .identity true false else .elem (a - b)
  beq a b := a == b

structure St where
  wz : Zip V
  rz : Zip V
  out : List String
  step : Nat

/-- Per-zipper fingerprint: relative path, origin, existence, value, child count, value count. -/
def fp (z : Zip V) : String :=
  hexPath z.path ++ " o" ++ hexPath z.focus ++ " e" ++ showBool z.pathExists ++
  " v" ++ showVal z.val ++ " c" ++ toString z.childCount ++ " n" ++ toString z.valCount

def emit (s : St) (name ret : String) : St :=
  { s with step := s.step + 1,
           out := (toString s.step ++ " " ++ name ++ " ret=" ++ ret ++
                   " W=" ++ fp s.wz ++ " R=" ++ fp s.rz) :: s.out }

def put (s : St) (t : Nat) (z : Zip V) : St :=
  if t == 0 then { s with wz := z } else { s with rz := z }

def nops : Nat := 49

def step (s : St) (d : Dec) : Option (St × Dec) := do
  let (opRaw, d) ← d.u8
  match opRaw.toNat % nops with
  | 0 => do
      let (t, d) ← d.mod 2
      let (a1, d) ← d.path
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "descend_to" tok, d)
      | none =>
        let (ret, z) := ((hexPath a1, z.descendTo a1))
        some (emit (put s t z) "descend_to" ret, d)
  | 1 => do
      let (t, d) ← d.mod 2
      let (a1, d) ← d.pathByte
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "descend_to_byte" tok, d)
      | none =>
        let (ret, z) := ((hexByte a1, z.descendToByte a1))
        some (emit (put s t z) "descend_to_byte" ret, d)
  | 2 => do
      let (t, d) ← d.mod 2
      let (a1, d) ← d.mod 8
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "ascend" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.ascend a1; (toString r, z))
        some (emit (put s t z) "ascend" ret, d)
  | 3 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "ascend_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.ascendByte; (showBool r, z))
        some (emit (put s t z) "ascend_byte" ret, d)
  | 4 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "reset" tok, d)
      | none =>
        let (ret, z) := (("-", z.reset))
        some (emit (put s t z) "reset" ret, d)
  | 5 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "descend_first_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendFirstByte; (showByteOpt r, z))
        some (emit (put s t z) "descend_first_byte" ret, d)
  | 6 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "descend_last_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendLastByte; (showByteOpt r, z))
        some (emit (put s t z) "descend_last_byte" ret, d)
  | 7 => do
      let (t, d) ← d.mod 2
      let (a1, d) ← d.mod 6
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "descend_indexed_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendIndexedByte a1; (showByteOpt r, z))
        some (emit (put s t z) "descend_indexed_byte" ret, d)
  | 8 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "descend_until" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendUntil; (showBool r, z))
        some (emit (put s t z) "descend_until" ret, d)
  | 9 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "ascend_until" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.ascendUntil; (toString r, z))
        some (emit (put s t z) "ascend_until" ret, d)
  | 10 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "ascend_until_branch" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.ascendUntilBranch; (toString r, z))
        some (emit (put s t z) "ascend_until_branch" ret, d)
  | 11 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "to_next_sibling_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.toNextSiblingByte; (showByteOpt r, z))
        some (emit (put s t z) "to_next_sibling_byte" ret, d)
  | 12 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "to_prev_sibling_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.toPrevSiblingByte; (showByteOpt r, z))
        some (emit (put s t z) "to_prev_sibling_byte" ret, d)
  | 13 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "to_next_step" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.toNextStep; (showBool r, z))
        some (emit (put s t z) "to_next_step" ret, d)
  | 14 => do
      let t := 1
      let z := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "to_next_val" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.toNextVal; (showBool r, z))
        some (emit (put s t z) "to_next_val" ret, d)
  | 15 => do
      let (a1, d) ← d.mod 4
      let t := 1
      let z := s.rz
      let sk : Option String := if (a1 == 0) then some "skip:k0" else none
      match sk with
      | some tok => some (emit s "descend_first_k_path" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendFirstKPath a1; (showBool r, z))
        some (emit (put s t z) "descend_first_k_path" ret, d)
  | 16 => do
      let (a1, d) ← d.mod 4
      let t := 1
      let z := s.rz
      let sk : Option String := if (a1 == 0) then some "skip:k0" else none
      match sk with
      | some tok => some (emit s "k_path_walk" tok, d)
      | none =>
        let (ret, z) := (let (ps, z) := kWalk z a1; (String.intercalate "," (ps.map hexPath), z))
        some (emit (put s t z) "k_path_walk" ret, d)
  | 17 => do
      let t := 1
      let z := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "descend_last_path" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendLastPath; (showBool r, z))
        some (emit (put s t z) "descend_last_path" ret, d)
  | 18 => do
      let (t, d) ← d.mod 2
      let (a1, d) ← d.path
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "move_to_path" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.moveToPath a1; (toString r, z))
        some (emit (put s t z) "move_to_path" ret, d)
  | 19 => do
      let (t, d) ← d.mod 2
      let (a1, d) ← d.path
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "descend_to_existing" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendToExisting a1; (toString r, z))
        some (emit (put s t z) "descend_to_existing" ret, d)
  | 20 => do
      let (t, d) ← d.mod 2
      let (a1, d) ← d.path
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "descend_to_val" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendToVal a1; (toString r, z))
        some (emit (put s t z) "descend_to_val" ret, d)
  | 21 => do
      let (t, d) ← d.mod 2
      let (a1, d) ← d.pathByte
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "descend_to_existing_byte" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendToExistingByte a1; (showBool r, z))
        some (emit (put s t z) "descend_to_existing_byte" ret, d)
  | 22 => do
      let (t, d) ← d.mod 2
      let (a1, d) ← d.mod 8
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "descend_until_max_bytes" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendUntilMaxBytes a1; (showBool r, z))
        some (emit (put s t z) "descend_until_max_bytes" ret, d)
  | 23 => do
      let (t, d) ← d.mod 2
      let (a1, d) ← d.path
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "descend_to_check" tok, d)
      | none =>
        let (ret, z) := (let (r, z) := z.descendToCheck a1; (showBool r, z))
        some (emit (put s t z) "descend_to_check" ret, d)
  | 24 => do
      let (t, d) ← d.mod 2
      let (a1, d) ← d.path
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := if t == 0 then some "skip:wz-gap" else none
      match sk with
      | some tok => some (emit s "val_at" tok, d)
      | none =>
        let (ret, z) := ((showVal (z.valAt a1), z))
        some (emit (put s t z) "val_at" ret, d)
  | 25 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "make_map_val_count" tok, d)
      | none =>
        let (ret, z) := ((toString (z.makeMap.valCount []), z))
        some (emit (put s t z) "make_map_val_count" ret, d)
  | 26 => do
      let (t, d) ← d.mod 2
      let z := if t == 0 then s.wz else s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "dump" tok, d)
      | none =>
        let (ret, z) := ((dumpAt z.trie z.focus, z))
        some (emit (put s t z) "dump" ret, d)
  | 27 => do
      let (a1, d) ← d.u8
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "set_val" tok, d)
      | none =>
        let (ret, z) := (let (o, z) := z.setVal (UInt64.ofNat a1.toNat); (showVal o, z))
        some (emit (put s t z) "set_val" ret, d)
  | 28 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "remove_val" tok, d)
      | none =>
        let (ret, z) := (let (o, z) := z.removeVal false; (showVal o, z))
        some (emit (put s t z) "remove_val" ret, d)
  | 29 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "create_path" tok, d)
      | none =>
        let (ret, z) := (let (b, z) := z.createPath; (showBool b, z))
        some (emit (put s t z) "create_path" ret, d)
  | 30 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := if (!z.root.isEmpty) then some "skip:off-root-prune" else none
      match sk with
      | some tok => some (emit s "prune_path" tok, d)
      | none =>
        let (ret, z) := (let (n, z) := z.prunePath; (toString n, z))
        some (emit (put s t z) "prune_path" ret, d)
  | 31 => do
      let (a1, d) ← d.u8
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "get_val_or_set_mut" tok, d)
      | none =>
        let (ret, z) := (let (v, z) := z.getValOrSetMut (UInt64.ofNat a1.toNat); (showVal (some v), z))
        some (emit (put s t z) "get_val_or_set_mut" ret, d)
  | 32 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "remove_branches" tok, d)
      | none =>
        let (ret, z) := (let e := z.focusNodeIsEmpty; let (b, z) := z.removeBranches false; (if e then "?" else showBool b, z))
        some (emit (put s t z) "remove_branches" ret, d)
  | 33 => do
      let (mn1, d) ← d.mod 4
      let (mb1, d) ← d.pathN mn1
      let a1 := ByteMask.ofList mb1
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "remove_unmasked_branches" tok, d)
      | none =>
        let (ret, z) := ((hexPath a1, z.removeUnmaskedBranches a1 false))
        some (emit (put s t z) "remove_unmasked_branches" ret, d)
  | 34 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "take_map_restore" tok, d)
      | none =>
        let (ret, z) := (let e := z.focusNodeIsEmpty && z.val.isNone; let (m, z) := z.takeMap false; match m with | some mm => (if e then "?" else "1", z.graftMap mm) | none => (if e then "?" else "0", z))
        some (emit (put s t z) "take_map_restore" ret, d)
  | 35 => do
      let (a1, d) ← d.path
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := if (a1.isEmpty) then some "skip:empty-path" else none
      match sk with
      | some tok => some (emit s "insert_prefix" tok, d)
      | none =>
        let (ret, z) := (let (b, z) := z.insertPrefix a1; (showBool b, z))
        some (emit (put s t z) "insert_prefix" ret, d)
  | 36 => do
      let (a1, d) ← d.mod 6
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "remove_prefix" tok, d)
      | none =>
        let (ret, z) := (let (b, z) := z.removePrefix a1; (showBool b, z))
        some (emit (put s t z) "remove_prefix" ret, d)
  | 37 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "graft" tok, d)
      | none =>
        let (ret, z) := (("-", z.graft r))
        some (emit (put s t z) "graft" ret, d)
  | 38 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "graft_map" tok, d)
      | none =>
        let (ret, z) := (("-", z.graftMap r.makeMap))
        some (emit (put s t z) "graft_map" ret, d)
  | 39 => do
      let (mn1, d) ← d.mod 4
      let (mb1, d) ← d.pathN mn1
      let a1 := ByteMask.ofList mb1
      let (a2, d) ← d.bool
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "graft_masked_branches" tok, d)
      | none =>
        let (ret, z) := ((hexPath a1 ++ ":" ++ showBool a2, z.graftMaskedBranches r a1 a2))
        some (emit (put s t z) "graft_masked_branches" ret, d)
  | 40 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "join_into" tok, d)
      | none =>
        let (ret, z) := (let (st, z) := z.joinInto ourOps r; (toString st, z))
        some (emit (put s t z) "join_into" ret, d)
  | 41 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "join_map_into" tok, d)
      | none =>
        let (ret, z) := (let e := z.focusNodeIsEmpty; let (st, z) := z.joinMapInto ourOps r.makeMap; (if e then "?" else toString st, z))
        some (emit (put s t z) "join_map_into" ret, d)
  | 42 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "meet_into" tok, d)
      | none =>
        let (ret, z) := (let (st, z) := z.meetInto ourOps r false; (toString st, z))
        some (emit (put s t z) "meet_into" ret, d)
  | 43 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "subtract_into" tok, d)
      | none =>
        let (ret, z) := (let (st, z) := z.subtractInto ourOps r false; (toString st, z))
        some (emit (put s t z) "subtract_into" ret, d)
  | 44 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "restrict" tok, d)
      | none =>
        let (ret, z) := (let e := z.focusNodeIsEmpty; let (st, z) := z.restrict ourOps r; (if e then "?" else toString st, z))
        some (emit (put s t z) "restrict" ret, d)
  | 45 => do
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := if (z.focusNodeIsEmpty || r.focusNodeIsEmpty) then some "skip:empty-focus" else none
      match sk with
      | some tok => some (emit s "restricting" tok, d)
      | none =>
        let (ret, z) := (let (b, z) := z.restricting r; (showBool b, z))
        some (emit (put s t z) "restricting" ret, d)
  | 46 => do
      let (a1, d) ← d.path
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "meet_2" tok, d)
      | none =>
        let (ret, z) := (let (st, z) := z.meet2 ourOps r { r with path := r.path ++ a1 }; (toString st, z))
        some (emit (put s t z) "meet_2" ret, d)
  | 47 => do
      let (a1, d) ← d.mod 4
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := none
      match sk with
      | some tok => some (emit s "join_k_path_into" tok, d)
      | none =>
        let (ret, z) := (let (b, z) := z.joinKPathInto ourOps a1 false; (if z.focusNodeIsEmpty then "?" else showBool b, z))
        some (emit (put s t z) "join_k_path_into" ret, d)
  | 48 => do
      let (a1, d) ← d.mod 4
      let t := 0
      let z := s.wz
      let r := s.rz
      let sk : Option String := if (a1 == 0) then some "skip:k0" else if (z.focusNodeIsEmpty) then some "skip:empty-focus" else none
      match sk with
      | some tok => some (emit s "meet_k_path_into" tok, d)
      | none =>
        let (ret, z) := (let (b, z) := z.meetKPathInto ourOps a1 false; (showBool b, z))
        some (emit (put s t z) "meet_k_path_into" ret, d)
  | _ => some (emit s "nop" "-", d)

def loop : Nat → St → Dec → St
  | 0, s, _ => s
  | n + 1, s, d =>
      match step s d with
      | some (s', d') => loop n s' d'
      | none => s

def header (d : Dec) : Option (St × Dec) := do
  let (n0, d) ← d.mod 8
  let (m0, d) ← seed PathMap.empty d n0
  let (n1, d) ← d.mod 8
  let (m1, d) ← seed PathMap.empty d n1
  let (r0, d) ← d.path 4
  let (r1, d) ← d.path 4
  let m0 := if r0.isEmpty then m0 else m0.addPath r0
  let m1 := if r1.isEmpty then m1 else m1.addPath r1
  some ({ wz := { trie := m0, root := r0, path := [] },
          rz := { trie := m1, root := r1, path := [] }, out := [], step := 0 }, d)

/-- Decode and run an input; the trace lines, then the final maps. -/
def run (bytes : ByteArray) (maxSteps : Nat := 256) : List String :=
  match header { bytes, pos := 0 } with
  | none => ["EMPTY"]
  | some (s0, d) =>
      let s := loop maxSteps s0 d
      s.out.reverse ++
        [ "MAP0 " ++ dumpAt s.wz.trie [], "MAP1 " ++ dumpAt s.rz.trie [],
          "ROOT0 " ++ hexPath s.wz.root, "ROOT1 " ++ hexPath s.rz.root ]

end SpecFuzz
end PathMapsSpec
