# gen_spec_ops.jl — generate BOTH sides of the PathMapsSpec differential harness from one table.
#
#   julia PathMap/tools/gen_spec_ops.jl        (no package environment needed: TOML is a stdlib)
#
# Reads   test/differential/spec/ops.toml
# Writes  lean/PathMapsSpec/SpecOps.lean              — the model side (then `cd lean && lake build`)
#         test/differential/spec/ops_generated.jl     — the Julia side (included by spec/SpecHarness.jl)
#
# WHY: upstream keeps its op table by hand in two languages ("the two must be changed together").
# Generating both from one list makes the decoding order, operand kinds, op codes, names and skip
# tokens identical by construction; only each side's semantics expression is written per language.
using TOML

const ROOT = normpath(joinpath(@__DIR__, ".."))
const SPEC = joinpath(ROOT, "test", "differential", "spec", "ops.toml")
const LEAN_OUT = joinpath(ROOT, "lean", "PathMapsSpec", "SpecOps.lean")
const JL_OUT = joinpath(ROOT, "test", "differential", "spec", "ops_generated.jl")

const LEAN_DECODE = Dict(
    "path" => "d.path",
    "byte" => "d.pathByte",
    "n8" => "d.mod 8",
    "i6" => "d.mod 6",
    "k4" => "d.mod 4",
)
const JL_DECODE = Dict(
    "path" => "dec_path!(d)",
    "byte" => "dec_pathbyte!(d)",
    "n8" => "dec_mod!(d, 8)",
    "i6" => "dec_mod!(d, 6)",
    "k4" => "dec_mod!(d, 4)",
)

leanstr(s) = "\"" * replace(s, "\\" => "\\\\", "\"" => "\\\"") * "\""

function check_op(op)
    for key in ("name", "operands", "lean", "julia")
        haskey(op, key) || error("op is missing `$key`: $(op)")
    end
    occursin(r"^[a-z_0-9]+$", op["name"]) || error("bad op name $(op["name"])")
    for k in op["operands"]
        haskey(LEAN_DECODE, k) || error("unknown operand kind $k in $(op["name"])")
    end
    for sk in get(op, "skip", Any[])
        startswith(sk["token"], "skip:") || error("skip token must start with skip: ($(op["name"]))")
    end
end

function gen_lean(ops, version)
    io = IOBuffer()
    println(io, """
-- GENERATED by PathMap/tools/gen_spec_ops.jl from test/differential/spec/ops.toml (version $version).
-- DO NOT EDIT. Change ops.toml and regenerate; the Julia side is generated from the same table.
import PathMapsSpec.Fuzz

/-!
# Our op table (`pathmaps-oracle --spec`)

The model side of the PathMapsSpec harness: decodes the wire format described in `ops.toml`, runs each
operation on the model's read zipper, and prints one trace line per step plus the final maps.
-/

namespace PathMapsSpec
namespace SpecFuzz
open Fuzz

structure St where
  m0 : PathMap V
  rz : Zip V
  out : List String
  step : Nat

/-- Per-step fingerprint: relative path, origin, existence, value, child count, value count. -/
def fp (z : Zip V) : String :=
  hexPath z.path ++ " o" ++ hexPath z.focus ++ " e" ++ showBool z.pathExists ++
  " v" ++ showVal z.val ++ " c" ++ toString z.childCount ++ " n" ++ toString z.valCount

def emit (s : St) (z : Zip V) (name ret : String) : St :=
  { s with rz := z, step := s.step + 1,
           out := (toString s.step ++ " " ++ name ++ " ret=" ++ ret ++ " R=" ++ fp z) :: s.out }

def nops : Nat := $(length(ops))

def step (s : St) (d : Dec) : Option (St × Dec) := do
  let (opRaw, d) ← d.u8
  let z := s.rz
  match opRaw.toNat % nops with""")
    for (i, op) in enumerate(ops)
        name = op["name"]
        println(io, "  | $(i - 1) => do")
        for (j, k) in enumerate(op["operands"])
            println(io, "      let (a$j, d) ← $(LEAN_DECODE[k])")
        end
        skips = get(op, "skip", Any[])
        chain = "none"
        for sk in reverse(skips)
            chain = "if ($(sk["lean"])) then some $(leanstr(sk["token"])) else $chain"
        end
        println(io, "      let sk : Option String := $chain")
        println(io, "      match sk with")
        println(io, "      | some tok => some (emit s z $(leanstr(name)) tok, d)")
        println(io, "      | none =>")
        println(io, "        let (ret, z) := ($(op["lean"]))")
        println(io, "        some (emit s z $(leanstr(name)) ret, d)")
    end
    println(io, """
  | _ => some (emit s z "nop" "-", d)

def loop : Nat → St → Dec → St
  | 0, s, _ => s
  | n + 1, s, d =>
      match step s d with
      | some (s', d') => loop n s' d'
      | none => s

def header (d : Dec) : Option (St × Dec) := do
  let (n0, d) ← d.mod 8
  let (m0, d) ← seed PathMap.empty d n0
  let (n1, d) ← d.mod 8
  let (m1, d) ← seed PathMap.empty d n1
  let (r0, d) ← d.path 4
  let (r1, d) ← d.path 4
  let m0 := if r0.isEmpty then m0 else m0.addPath r0
  let m1 := if r1.isEmpty then m1 else m1.addPath r1
  some ({ m0 := m0, rz := { trie := m1, root := r1, path := [] }, out := [], step := 0 }, d)

/-- Decode and run an input; the trace lines, then the final maps. -/
def run (bytes : ByteArray) (maxSteps : Nat := 256) : List String :=
  match header { bytes, pos := 0 } with
  | none => ["EMPTY"]
  | some (s0, d) =>
      let s := loop maxSteps s0 d
      s.out.reverse ++
        [ "MAP0 " ++ dumpAt s.m0 [], "MAP1 " ++ dumpAt s.rz.trie [],
          "ROOT1 " ++ hexPath s.rz.root ]

end SpecFuzz
end PathMapsSpec""")
    String(take!(io))
end

function gen_julia(ops, version)
    io = IOBuffer()
    println(io, """
# GENERATED by PathMap/tools/gen_spec_ops.jl from test/differential/spec/ops.toml (version $version).
# DO NOT EDIT. Change ops.toml and regenerate; the Lean side is generated from the same table.

const SPEC_VERSION = $version
const NOPS = $(length(ops))
const OP_NAMES = $(repr([op["name"] for op in ops]))

\"\"\"
    spec_step!(st, d) -> Bool

Decode and run one operation on `st.rz`, appending its trace line. `false` means the input ran out
mid-operation, which ends the program (same rule as the model).
\"\"\"
function spec_step!(st::SpecState, d::Dec)
    raw = dec_u8!(d)
    raw === nothing && return false
    op = Int(raw) % NOPS
    z = st.rz""")
    for (i, op) in enumerate(ops)
        name = op["name"]
        println(io, "    $(i == 1 ? "if" : "elseif") op == $(i - 1)   # $name")
        for (j, k) in enumerate(op["operands"])
            println(io, "        a$j = $(JL_DECODE[k])")
            println(io, "        a$j === nothing && return false")
        end
        skips = get(op, "skip", Any[])
        if isempty(skips)
            println(io, "        sk = nothing")
        else
            chain = "nothing"
            for sk in reverse(skips)
                chain = "($(sk["julia"])) ? $(repr(sk["token"])) : $chain"
            end
            println(io, "        sk = $chain")
        end
        println(io, "        emit!(st, $(repr(name)), sk === nothing ? ($(op["julia"])) : sk)")
    end
    println(io, """
    else
        emit!(st, "nop", "-")
    end
    true
end""")
    String(take!(io))
end

function main()
    spec = TOML.parsefile(SPEC)
    version = spec["version"]
    ops = spec["op"]
    foreach(check_op, ops)
    length(unique(op["name"] for op in ops)) == length(ops) || error("duplicate op names")
    write(LEAN_OUT, gen_lean(ops, version))
    write(JL_OUT, gen_julia(ops, version))
    println("gen_spec_ops: $(length(ops)) ops (version $version) -> ", relpath(LEAN_OUT, ROOT), ", ", relpath(JL_OUT, ROOT))
end

main()
