# gen_spec_ops.jl — generate BOTH sides of the PathMapsSpec differential harness from one table.
#
#   julia PathMap/tools/gen_spec_ops.jl        (no package environment needed: TOML is a stdlib)
#
# Reads   test/differential/spec/ops.toml
# Writes  lean/PathMapsSpec/SpecOps.lean              — the model side (then `cd lean && lake build`)
#         test/differential/spec/ops_generated.jl     — the Julia side (included by spec/SpecHarness.jl)
#
# WHY: upstream keeps its op table by hand in two languages ("the two must be changed together").
# Generating both from one list makes the decoding order, operand kinds, op codes, names and skip
# tokens identical by construction; only each side's semantics expression is written per language.
using TOML

const ROOT = normpath(joinpath(@__DIR__, ".."))
const SPEC = joinpath(ROOT, "test", "differential", "spec", "ops.toml")
const LEAN_OUT = joinpath(ROOT, "lean", "PathMapsSpec", "SpecOps.lean")
const JL_OUT = joinpath(ROOT, "test", "differential", "spec", "ops_generated.jl")

const SIMPLE_KINDS = Dict(
    # kind => (Lean decode, Julia decode)
    "path" => ("d.path", "dec_path!(d)"),
    "byte" => ("d.pathByte", "dec_pathbyte!(d)"),
    "n8" => ("d.mod 8", "dec_mod!(d, 8)"),
    "i6" => ("d.mod 6", "dec_mod!(d, 6)"),
    "k4" => ("d.mod 4", "dec_mod!(d, 4)"),
    "u8" => ("d.u8", "dec_u8!(d)"),
    "bool" => ("d.bool", "dec_bool!(d)"),
    "mask" => ("", "dec_mask!(d)"),     # Lean side is two binds, see lean_decode
)
const TARGETS = ("rw", "r", "w")

leanstr(s) = "\"" * replace(s, "\\" => "\\\\", "\"" => "\\\"") * "\""

function lean_decode(io, j, k, indent)
    if k == "mask"
        println(io, indent, "let (mn$j, d) ← d.mod 4")
        println(io, indent, "let (mb$j, d) ← d.pathN mn$j")
        println(io, indent, "let a$j := ByteMask.ofList mb$j")
    else
        println(io, indent, "let (a$j, d) ← ", SIMPLE_KINDS[k][1])
    end
end

function check_op(op)
    for key in ("name", "target", "operands", "lean", "julia")
        haskey(op, key) || error("op is missing `$key`: $(op)")
    end
    occursin(r"^[a-z_0-9]+$", op["name"]) || error("bad op name $(op["name"])")
    op["target"] in TARGETS || error("bad target $(op["target"]) in $(op["name"])")
    haskey(op, "wz_gap") && op["target"] != "rw" && error("wz_gap only applies to rw ops ($(op["name"]))")
    for k in op["operands"]
        haskey(SIMPLE_KINDS, k) || error("unknown operand kind $k in $(op["name"])")
    end
    for sk in get(op, "skip", Any[])
        startswith(sk["token"], "skip:") || error("skip token must start with skip: ($(op["name"]))")
    end
end

skip_chain(skips, lang, none_word, fmt) =
    foldr((sk, acc) -> fmt(sk[lang], sk["token"], acc), skips; init = none_word)

lean_chain(skips) = skip_chain(skips, "lean", "none",
    (c, t, acc) -> "if ($c) then some $(leanstr(t)) else $acc")
julia_chain(skips) = skip_chain(skips, "julia", "nothing",
    (c, t, acc) -> "($c) ? $(repr(t)) : $acc")

function gen_lean(ops, version)
    io = IOBuffer()
    println(io, """
-- GENERATED by PathMap/tools/gen_spec_ops.jl from test/differential/spec/ops.toml (version $version).
-- DO NOT EDIT. Change ops.toml and regenerate; the Julia side is generated from the same table.
import PathMapsSpec.Fuzz
import PathMapsSpec.Write

/-!
# Our op table (`pathmaps-oracle --spec`)

The model side of the PathMapsSpec harness: decodes the wire format described in `ops.toml`, runs each
operation on the model's write zipper (`wz`, over map0) or read zipper (`rz`, over map1), and prints one
trace line per step plus the final maps.
-/

set_option linter.unusedVariables false

namespace PathMapsSpec
namespace SpecFuzz
open Fuzz

/-- OUR `UInt64` lattice (`src/core/Ring.jl`): join = max, meet = min, subtract = saturating, with
the identity masks our implementation reports. Upstream's `u64Ops` is a placeholder we do not follow. -/
def ourOps : ValOps UInt64 where
  pjoin a b := if a == b then .identity true true else if a > b then .identity true false else .identity false true
  pmeet a b := if a == b then .identity true true else if a < b then .identity true false else .identity false true
  psub a b := if b >= a then .none else if b == 0 then .identity true false else .elem (a - b)
  beq a b := a == b

structure St where
  wz : Zip V
  rz : Zip V
  out : List String
  step : Nat

/-- Per-zipper fingerprint: relative path, origin, existence, value, child count, value count. -/
def fp (z : Zip V) : String :=
  hexPath z.path ++ " o" ++ hexPath z.focus ++ " e" ++ showBool z.pathExists ++
  " v" ++ showVal z.val ++ " c" ++ toString z.childCount ++ " n" ++ toString z.valCount

def emit (s : St) (name ret : String) : St :=
  { s with step := s.step + 1,
           out := (toString s.step ++ " " ++ name ++ " ret=" ++ ret ++
                   " W=" ++ fp s.wz ++ " R=" ++ fp s.rz) :: s.out }

def put (s : St) (t : Nat) (z : Zip V) : St :=
  if t == 0 then { s with wz := z } else { s with rz := z }

def nops : Nat := $(length(ops))

def step (s : St) (d : Dec) : Option (St × Dec) := do
  let (opRaw, d) ← d.u8
  match opRaw.toNat % nops with""")
    for (i, op) in enumerate(ops)
        name, tgt = op["name"], op["target"]
        ind = "      "
        println(io, "  | $(i - 1) => do")
        tgt == "rw" && println(io, ind, "let (t, d) ← d.mod 2")
        for (j, k) in enumerate(op["operands"])
            lean_decode(io, j, k, ind)
        end
        if tgt == "rw"
            println(io, ind, "let z := if t == 0 then s.wz else s.rz")
        elseif tgt == "r"
            println(io, ind, "let t := 1")
            println(io, ind, "let z := s.rz")
        else
            println(io, ind, "let t := 0")
            println(io, ind, "let z := s.wz")
            println(io, ind, "let r := s.rz")
        end
        chain = lean_chain(get(op, "skip", Any[]))
        haskey(op, "wz_gap") && (chain = "if t == 0 then some \"skip:wz-gap\" else $chain")
        println(io, ind, "let sk : Option String := $chain")
        println(io, ind, "match sk with")
        println(io, ind, "| some tok => some (emit s $(leanstr(name)) tok, d)")
        println(io, ind, "| none =>")
        println(io, ind, "  let (ret, z) := ($(op["lean"]))")
        println(io, ind, "  some (emit (put s t z) $(leanstr(name)) ret, d)")
    end
    println(io, """
  | _ => some (emit s "nop" "-", d)

def loop : Nat → St → Dec → St
  | 0, s, _ => s
  | n + 1, s, d =>
      match step s d with
      | some (s', d') => loop n s' d'
      | none => s

def header (d : Dec) : Option (St × Dec) := do
  let (n0, d) ← d.mod 8
  let (m0, d) ← seed PathMap.empty d n0
  let (n1, d) ← d.mod 8
  let (m1, d) ← seed PathMap.empty d n1
  let (r0, d) ← d.path 4
  let (r1, d) ← d.path 4
  let m0 := if r0.isEmpty then m0 else m0.addPath r0
  let m1 := if r1.isEmpty then m1 else m1.addPath r1
  some ({ wz := { trie := m0, root := r0, path := [] },
          rz := { trie := m1, root := r1, path := [] }, out := [], step := 0 }, d)

/-- Decode and run an input; the trace lines, then the final maps. -/
def run (bytes : ByteArray) (maxSteps : Nat := 256) : List String :=
  match header { bytes, pos := 0 } with
  | none => ["EMPTY"]
  | some (s0, d) =>
      let s := loop maxSteps s0 d
      s.out.reverse ++
        [ "MAP0 " ++ dumpAt s.wz.trie [], "MAP1 " ++ dumpAt s.rz.trie [],
          "ROOT0 " ++ hexPath s.wz.root, "ROOT1 " ++ hexPath s.rz.root ]

end SpecFuzz
end PathMapsSpec""")
    String(take!(io))
end

function julia_branch(io, op, which, ind)
    name = op["name"]
    if which == "w"
        println(io, ind, "z = st.wz")
        println(io, ind, "r = st.rz")
    else
        println(io, ind, "z = st.", which == "t0" ? "wz" : "rz")
    end
    if which == "t0" && haskey(op, "wz_gap")
        println(io, ind, "emit!(st, $(repr(name)), \"skip:wz-gap\")")
        return
    end
    println(io, ind, "sk = ", julia_chain(get(op, "skip", Any[])))
    println(io, ind, "emit!(st, $(repr(name)), sk === nothing ? ($(op["julia"])) : sk)")
end

function gen_julia(ops, version)
    io = IOBuffer()
    println(io, """
# GENERATED by PathMap/tools/gen_spec_ops.jl from test/differential/spec/ops.toml (version $version).
# DO NOT EDIT. Change ops.toml and regenerate; the Lean side is generated from the same table.

const SPEC_VERSION = $version
const NOPS = $(length(ops))
const OP_NAMES = $(repr([op["name"] for op in ops]))

\"\"\"
    spec_step!(st, d) -> Bool

Decode and run one operation, appending its trace line. `false` means the input ran out
mid-operation, which ends the program (same rule as the model). A `rw` op is generated once per
zipper type, so each branch is type-stable and dispatches to that zipper's methods.
\"\"\"
function spec_step!(st::SpecState, d::Dec)
    raw = dec_u8!(d)
    raw === nothing && return false
    op = Int(raw) % NOPS
    st.cur = op""")
    for (i, op) in enumerate(ops)
        println(io, "    $(i == 1 ? "if" : "elseif") op == $(i - 1)   # $(op["name"])")
        tgt = op["target"]
        if tgt == "rw"
            println(io, "        t = dec_mod!(d, 2)")
            println(io, "        t === nothing && return false")
        end
        for (j, k) in enumerate(op["operands"])
            println(io, "        a$j = $(SIMPLE_KINDS[k][2])")
            println(io, "        a$j === nothing && return false")
        end
        if tgt == "rw"
            println(io, "        if t == 0")
            julia_branch(io, op, "t0", "            ")
            println(io, "        else")
            julia_branch(io, op, "t1", "            ")
            println(io, "        end")
        else
            julia_branch(io, op, tgt == "w" ? "w" : "t1", "        ")
        end
    end
    println(io, """
    else
        emit!(st, "nop", "-")
    end
    true
end""")
    String(take!(io))
end

function main()
    spec = TOML.parsefile(SPEC)
    version = spec["version"]
    ops = spec["op"]
    foreach(check_op, ops)
    length(unique(op["name"] for op in ops)) == length(ops) || error("duplicate op names")
    write(LEAN_OUT, gen_lean(ops, version))
    write(JL_OUT, gen_julia(ops, version))
    println("gen_spec_ops: $(length(ops)) ops (version $version) -> ", relpath(LEAN_OUT, ROOT), ", ", relpath(JL_OUT, ROOT))
end

main()
